### ISSUE TITLE
2021 Release Checklist

### ISSUE THREAD

**Issue by Lnk2past** [Lnk2past/copperhead#13]
Checklist for things to be done for a 2021.m.x release

- [ ] Incorporate new design for templating generated modules
- [ ] Incorporate `std::complex` support
- [ ] Incorporate NumPy support
- [ ] Update documentation
- [ ] Hash function inputs for caching/determining rebuild
- [x] Fix Xcode support #12 
- [ ] Change `master` to `main` (not needed for a release, but something to be done)

Most of this work is complete, but scattered across branches both local and remote. Need to consolidate, cleanup, and integrate into main code base.
